global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#bogdan_bolshakov'
