version: '3.3'
services:

  post_db:
    image: mongo:${MONGO_VERSION}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
      monitoring_2:

  ui:
    image: ${USER_NAME}/ui:${ui_ver}
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    ports:
    #  - ${EXT_PORT}:9292/tcp
      - 9292:9292/tcp
    networks:
      - back_net
      - front_net
      - monitoring_2
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post

  post:
    image: ${USER_NAME}/post:${post_ver}
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    networks:
      - back_net
      - front_net
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post
  
  comment:
    image: ${USER_NAME}/comment:${comment_ver}
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    networks:
      - back_net
      - front_net
      - monitoring_2

volumes:
  post_db:

networks:
  back_net:
  front_net:
  monitoring_2:
