version: '3.3'
services:
  post_db:
    image: mongo:${MONGO_VERSION}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
      monitoring_2:
  ui:
    image: ${USER_NAME}/ui
    ports:
    #  - ${EXT_PORT}:9292/tcp
      - 9292:9292/tcp
    networks:
      - front_net
      - monitoring_2
  post:
    image: ${USER_NAME}/post
    networks:
      - back_net
      - front_net
      - monitoring_2
  comment:
    image: ${USER_NAME}/comment
    networks:
      - back_net
      - front_net
      - monitoring_2

volumes:
  post_db:

networks:
  back_net:
  front_net:
  monitoring_2:
